export const IMPORT_ERROR_CODES = {
  INVALID_ROW: 'INVALID_ROW',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  DUPLICATE_BROKER_ORDER_IN_FILE: 'DUPLICATE_BROKER_ORDER_IN_FILE',
  /** @deprecated Prefer DUPLICATE_BROKER_ORDER_ALREADY_IMPORTED for skipped DB duplicates. */
  DUPLICATE_BROKER_ORDER_IN_ACCOUNT: 'DUPLICATE_BROKER_ORDER_IN_ACCOUNT',
  /** Existing account + brokerOrderNo — preview/commit status is `skipped`, not error. */
  DUPLICATE_BROKER_ORDER_ALREADY_IMPORTED: 'DUPLICATE_BROKER_ORDER_ALREADY_IMPORTED',
  UNSUPPORTED_CURRENCY: 'UNSUPPORTED_CURRENCY',
  CURRENCY_MISMATCH: 'CURRENCY_MISMATCH',
  ASSET_ALIAS_NOT_FOUND: 'ASSET_ALIAS_NOT_FOUND',
  ACCOUNT_NOT_BROKER: 'ACCOUNT_NOT_BROKER',
  UNSUPPORTED_BROKER: 'UNSUPPORTED_BROKER',
  ACCOUNT_NOT_FOUND_OR_FORBIDDEN: 'ACCOUNT_NOT_FOUND_OR_FORBIDDEN',
  COMMIT_NOT_ALLOWED_WITH_ERRORS: 'COMMIT_NOT_ALLOWED_WITH_ERRORS',
  IMPORT_COMMIT_FAILED: 'IMPORT_COMMIT_FAILED',
} as const

export type ImportErrorCode =
  (typeof IMPORT_ERROR_CODES)[keyof typeof IMPORT_ERROR_CODES]
